### ISSUE TITLE
从站方式 canfestival receive faild, err = 0

### ISSUE THREAD

**Issue by maikebing** [gbcwbz/canfestival-rtt#12]
[\src\can_rtthread.c](https://github.com/gbcwbz/canfestival-rtt/blob/a95f86e6659983c843b4b7d84a5ab63a11904b80/src/can_rtthread.c#L110)   
这里读不到数据。

**Comment by maikebing** [comment]
https://github.com/zhangtag/CANOpen_STM32F4_RTThread  这个从机 就是没问题的。 修改比较乱， 暂时还没对比出去来 真正最细节的问题原因。

**Comment by gbcwbz** [comment]
是不是波特率的问题，rtthread 4.0.5 版本的 407 can 驱动有问题，APB 时钟和 407的不一样

**Comment by maikebing** [comment]
这个我倒是没太注意到。 我切4.10了。
