### ISSUE TITLE
请问一下为什么没有开启调试输出的选项

### ISSUE THREAD

**Issue by wdfk-prog** [gbcwbz/canfestival-rtt#13]
在applicfg.h中已经对
MSG_WAR和MSG_ERR做了支持
为什么没有RT_CONFIG中没有配置选项呢？
是开启了有什么bug吗？

我尝试打开选项,输出中开头和结尾的数字好像没有意义。
```c
09-23 15:58:32 W/switchCommunicationState cf_timer: 0x9999 None 9999
09-23 16:00:35 W/switchCommunicationState cf_timer: 0x9999 startSYNC(d) 9999
09-23 16:00:35 W/switchCommunicationState cf_timer: 0x9999 lifeGuardInit(d) 9999
09-23 16:00:35 W/switchCommunicationState cf_timer: 0x9999 emergencyInit(d) 9999
09-23 16:00:35 W/switchCommunicationState cf_timer: 0x9999 slaveSendBootUp(d) 9999
09-23 16:00:35 W/slaveSendBootUp cf_timer: 0x3407 Send a Boot-Up msg  0
```

**Comment by gbcwbz** [comment]
- 开启之后需要在`.c`文件里添加 `#include <rtdbg.h>`，不想在 `applicfg.h`中添加，因为会导致所有使用canfestival的文件都 include
- 可以在`src/*.c`里面都添加`#include <rtdbg.h>`，但是这样就会修改很多 canfestival的文件，所以还没有做

**Comment by wdfk-prog** [comment]
> * 开启之后需要在`.c`文件里添加 `#include <rtdbg.h>`，不想在 `applicfg.h`中添加，因为会导致所有使用canfestival的文件都 include
> * 可以在`src/*.c`里面都添加`#include <rtdbg.h>`，但是这样就会修改很多 canfestival的文件，所以还没有做

这样啊，好吧。
另外我想问一下objdictedit这个工具导入EDS字典有问题。这个工具有更新的吗？我从官网拉下来的工具打开一些EDS字典会报错。

**Comment by gbcwbz** [comment]
- EDS 我没用过，都是用 objdictedit 生成的 .od 文件
- 我现在用的这个 [objdictgen](https://github.com/gbcwbz/objdictgen)，可以在github上找找有没有新的

**Comment by wdfk-prog** [comment]
> 

多谢。
