### ISSUE TITLE
关于心跳时间部分的问题

### ISSUE THREAD

**Issue by wdfk-prog** [gbcwbz/canfestival-rtt#14]
1. canopen_start_thread_entry函数分明只运行一遍。为什么不写成函数而是使用线程形式？
2.  为什么例程没有使用主机去发送心跳包？
对于电机控制来说，应该是电机（从机）需要判断主机是否掉线，然后刹车报警更加重要吧。
主机判断从机离线，只能发出报警而已。
是否按照consumer_heartbeat_time 这样写入就可以了？
3. config_servo_param函数中我要自己添加参数，为什么只能新增case发送出去，不能一个case多个发送呢？查询一下发现是getSDOlineOnUse错误。是因为只用了一个sdo的原因吗？

**Comment by wdfk-prog** [comment]
另一个不明白的地方
问题点：1400h默认值CAN-ID： 200h + Node-ID
字典文件设置为0x00000182
1800h默认 值CAN-ID： 180h + Node-ID
字典文件设置为0x00000202
修正回来无法通信
为什么要这样设置？

**Comment by gbcwbz** [comment]
1. 之前是在主站初始化和收到从站bootup信息的时候调用的，想支持多个从站同时配置，写成函数也可以
2. 我用到的伺服在断线后可以自动停机的，不需要主站心跳，因为是用的同步模式；如果你用的伺服需要的话也可以配置成主站发心跳包。这个只是一个示例，不能满足所有要求。具体设置要看CiA 301,应该是设置主站的 producer heartbeat time和从站的consumer heartbeat time
3. 看起来同时只能用一个，这个是参考的canfestival的例子写的，有操作系统的地方完全可以写成阻塞式的（writeNetworkDictCallBack 后 take sem, 回调中 release sem），这样就不用写case了
4. 1400 是Receive PDO 1，从站的接收ID,要对应主站的发送ID,字典里面的配置是主站的，config_servo_param 里面是配置的从站的

**Comment by wdfk-prog** [comment]
> 
感谢回复。
我的伺服有支持同步模式，但是是在ethcat模式下的，估计用不了。
同步模式下为什么不需要主机发送心跳呢？是判断有无pdo传输吗？

**Comment by gbcwbz** [comment]
我说的同步模式是指can总线的SYNC报文，可能从站是根据SYNC有没有收到判断的

**Comment by wdfk-prog** [comment]
> 我说的同步模式是指can总线的SYNC报文，可能从站是根据SYNC有没有收到判断的

多谢^-^
