### ISSUE TITLE
 DS402中插补位置模式( Interpolation Position Mode)如何实现

### ISSUE THREAD

**Issue by wdfk-prog** [gbcwbz/canfestival-rtt#18]
# DS402中插补位置模式( Interpolation Position Mode)如何实现？
## 配置后进入插补模式，电机报警。
报警原因:通讯同步信号超时 
![image](https://user-images.githubusercontent.com/66928464/197091910-4b217b2b-8662-4584-a7d4-800ffce97885.png)

### 操作流程根据电机手册操作步骤配置： 
1. 设定模式，OD 6060h = 07h，为插补位置模式。 
2. 设定插补周期 OD 60C2h，设定需与通讯周期 OD 1006h相同。 
3. 于上位机内的 PDO映像设定内，配置其中一组 RxPDO为 OD 60C1h sub1与 
OD 60C1h sub2。 
4. 于上位机内的 PDO映射设定内，依照需求配置需要监看的对象至 TxPDO内， 
如回授位置 (OD 6064h) 等信息。 
5. 设定控制指令 OD 6040h，请依照以下步骤操作。步骤 5.1与 5.2是为了使驱动器的
状态机 (state machine) 进入准备状态

### 查看PDO周期平均10.044ms
- 按理说不应该通信超时
![image](https://user-images.githubusercontent.com/66928464/197091532-2bd2908b-76fe-4b10-8c81-2e81d0404b57.png)

### 现象
- Modes_of_operation 选择 INTERPOLATED_POSITION_MODE;
- 写入电机60C2h设置值，0X60C2 = 1*10^-2=0.01S=10MS
![image](https://user-images.githubusercontent.com/66928464/197092472-fbd1708e-e985-4105-bccb-7ef696bb6545.png)
![image](https://user-images.githubusercontent.com/66928464/197092376-d194a1ff-339f-4768-9d4d-5b16d4ff0088.png)
- Controlword设置为ENABLE_OPERATION后，电机启动有声响。
![image](https://user-images.githubusercontent.com/66928464/197093520-331a5ebc-a753-4e75-b541-818aa7eaac48.png)
![image](https://user-images.githubusercontent.com/66928464/197094106-d9c052b4-aba8-4ecd-be9b-3fd356cb2abf.png)

  * SUBINDEX1:16位,占用2个字节.即1F 00  Controlword (0x6040)
  * SUBINDEX2: 8位,占用1个字节.即07     Modes of operation (0x6060)
  * SUBINDEX3:32位,占用4个字节.即2C 01 00 00    Pos_Cmd (0x60C1)
 
- 运行一次后停止，电机报警
![image](https://user-images.githubusercontent.com/66928464/197094007-3df19287-4d15-4388-a027-decab2cd94a7.png)

### 怀疑错误原因
- 根据报警代码，怀疑为周期超时。但接入分析仪查看周期没有超时。
- 怀疑0X60C1需要两个子索引。
   添加子索引2之后，电机配置时返回错误代码。
- 怀疑0X60C1需要不断发送不同位置指令，没有发送不同指令报错。

###代码如下
```c
static void motor_on_interpolated_position(void)
{
//    int nodeId = 1;
//    if(argc > 1) {
//        nodeId = atoi(argv[1]);
//    }
//    (void)nodeId;
  extern void Write_SLAVE_Interpolation_time_period(uint8_t nodeId);
  Write_SLAVE_Interpolation_time_period(SERVO_NODEID);
  
  Modes_of_operation = INTERPOLATED_POSITION_MODE;
  
	Controlword = CONTROL_WORD_SHUTDOWN;
  SYNC_DELAY;
	Controlword = CONTROL_WORD_SWITCH_ON;
  SYNC_DELAY;
  /*State Transition 1: NO IP-MODE SELECTED => IP-MODE INACTIVE
  Event: Enter in the state OPERATION ENABLE with controlword and select ip 
  mode with modes of operation*/
//	Controlword = CONTROL_WORD_ENABLE_OPERATION & ~ENABLE_IP_MODE;
//  SYNC_DELAY;
}
static void motor_interpolation_position (void)
{
  /* State Transition 3: IP-MODE INACTIVE => IP-MODE ACTIVE
  Event: Set bit enable ip mode (bit4) of the controlword while in ip mode and 
  OPERATION ENABLE*/
  Controlword = CONTROL_WORD_ENABLE_OPERATION | ENABLE_IP_MODE;//Bit 4切至 on。 

  for(uint16_t i = 0; i < 1000;i++)
  {
    Interpolation_data_record_Parameter1_of_ip_function += 100;
    rt_thread_mdelay(1);
  }

}
```

**Comment by gbcwbz** [comment]
- 在进入OP之前有没有把当前位置赋给60c1
- 60c1的值如果一直不变化是不会报警的，只会停在当前位置
- 确保SYNC信号和你的插补周期相同

**Comment by wdfk-prog** [comment]
> * 在进入OP之前有没有把当前位置赋给60c1
> * 60c1的值如果一直不变化是不会报警的，只会停在当前位置
> * 确保SYNC信号和你的插补周期相同

- “在进入OP之前有没有把当前位置赋给60c1” ，这一点的话，当前位置赋给60C1什么意思？。我赋值0可以吧，PDO会自动传输过去的。
- SYNC与插补周期一致，
![40cb80b2bc1516dfa1772888f566d17](https://user-images.githubusercontent.com/66928464/198912561-80e56a71-8115-4707-904a-aaad8520bd52.jpg)

**Comment by gbcwbz** [comment]
就是把当前位置给目标位置，如果当前位置很大（比如10000圈）,目标位置给0,电机会在一个周期内走到目标位置，会产生冲击，你看一下伺服手册，应该有这个注意事项

**Comment by wdfk-prog** [comment]
> 
这个方面我有注意到。
- 在我使能了插补模式后，如果当前位置差别很大，电机会转一下，然后停止。然后电机报警显示误差过大。
- 如果位置差别不大，我会没有感受到电机转动，然后报警显示通讯同步信号超时。
- 按照电机能转动一下来说，我应该是配置成功的。但不知道为什么后续会显示超时

**Comment by wdfk-prog** [comment]
> 就是把当前位置给目标位置，如果当前位置很大（比如10000圈）,目标位置给0,电机会在一个周期内走到目标位置，会产生冲击，你看一下伺服手册，应该有这个注意事项

另外主站TPDO和从站RPDO之间的设置需要怎么配置？
我主站和从站PDO配置都配成如下
![image](https://user-images.githubusercontent.com/66928464/198914495-a1050186-477b-46fc-8168-1caed1fb1740.png)

**Comment by rsnGON** [comment]
@wdfk-prog 兄弟最后怎么解决的报错啊～ _～
